---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-thinkpad
# description will be included in the image's metadata
description: bluefin-dx for Thinkad T14 Gen 4 AMD

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - thinkfan

  - type: files
    files:
      - source: system_after
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: systemd
    system:
      enabled:
        - thinkfan

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

